Feature/#108 통계 페이지 원 그래프 제작(타입 미완성)
prgrms-web-devcourse/Team-10jo-10wonmoa-FE pull request #121
Opened 2022-08-07 12:19 UTC by hyunjin0910

# 개요

d3 타입을 지정하는 부분이 어렵네요;
우선 페이지 다른 부분 완성하려고 PR 날립니다

# 작업 내용

# 사진 (UI 컴포넌트 및 파일에 한해)
![image](https://user-images.githubusercontent.com/95457808/183290199-9e3b1391-5a13-48b4-837c-64dc072a1853.png)
![image](https://user-images.githubusercontent.com/95457808/183290214-7d098db8-8f2d-4297-ab26-5d642a2d2cb3.png)

# 중점적으로 봐줬으면 하는 부분 (선택 사항)
close #108

2022-08-07 15:45 UTC, violet9503 commented on src/components/statistic/PieChart.tsx
> +interface Data {
라이브러리를 타입스크립트로 사용하려면 `@types/{라이브러리명}` 으로 깔아서 하는 편인데 d3도 검색해보니까 있어서 한번 시도해보시면 좋을 것 같아요~ 직접 타입 다 지정하시는 것 같아보여서요

2022-08-07 18:25 UTC, dahye1013 requested changes
차트 구현이 굉장히 빠르시네요 ㅎㅎ 
 저도 비올레와 같이 라이브러리에 해당하는 @types를 사용해보시는걸 추천 드려요.
그리고 CI에 lint 에러가 몇개 걸리는데 이것만 수정해주시면 좋을 것 같네용!

2022-08-07 18:25 UTC, dahye1013 commented on src/components/statistic/PieChart.tsx
> +  //data?: PieData[];
요기는 제거해주시면 될 것 같네용!

2022-08-07 18:25 UTC, dahye1013 commented on src/components/statistic/PieChart.tsx
> +  createArc?: any;
any가 있네요! 이름을 보니 메소드 같은데 () => void 요런식으로 형태를 지정해주면 어떨까요?

2022-08-09 14:51 UTC, sa02045 commented on src/pages/statistic/index.tsx
> +import * as d3 from 'd3';
이런식으로 작성하면 트리쉐이킹 되나요?

2022-08-09 15:08 UTC, dahye1013 approved these changes

2022-08-09 15:08 UTC, merged